export const redirects = [
    "omnichannel-marketing-boosting-customer-experiences-for-clients",
    "omnichannel-reputation-management-protecting-your-online-presence",
    "what-is-omnichannel-performance-marketing",
    "maximizing-roi-with-omnichannel-marketing-strategies-and-best-practices",
    "the-role-of-ai-in-omnichannel-marketing-opportunities-and-challenges",
    "creating-a-seamless-omnichannel-customer-experience-a-step-by-step-guide",
    "the-importance-of-omnichannel-marketing-in-todays-business-landscape-tapouts-co",
    "omnichannel-marketing-vs-multi-channel-marketing-whats-the-difference",
    "the-role-of-omnichannel-reputation-management-in-building-brand-trust-tapouts-co",
    "how-to-develop-an-omnichannel-marketing-strategy-that-drives-results-tapouts-co",
    "the-benefits-of-omnichannel-marketing-for-small-businesses",
    "the-future-of-omnichannel-marketing-trends-and-predictions",
    "best-practices-for-managing-your-brands-reputation-across-multiple-channels",
    "the-impact-of-social-media-on-omnichannel-reputation-management-and-how-to-manage-it",
    "omnichannel-marketing-strategy-a-comprehensive-guide-by-tapouts-co",
    "the-importance-of-hiring-a-digital-marketing-agency-for-your-business-in-the-uk",
    "maximizing-your-online-presence-with-the-best-digital-marketing-strategies-in-the-uk",
    "unleashing-your-business-potential-with-the-expertise-of-a-digital-marketing-agency-in-the-uk",
    "understanding-the-importance-of-seo-for-business-growth-and-how-an-seo-agency-can-help",
    "the-role-of-an-seo-agency-in-enhancing-your-online-visibility-and-website-ranking",
    "omnichannel-marketing-strategy-revolutionizing-customer-engagement",
    "omnichannel-marketing-delivering-seamless-customer-experiences",
    "omnichannel-marketing-agency-unlocking-success-for-your-business",
    "omnichannel-marketing-examples",
    "the-rise-of-the-omnichannel-market-revolutionizing-the-customer-experience",
    "best-omnichannel-marketing-software-boost-your-marketing-efforts",
    "how-does-omnichannel-marketing-work",
    "integrated-marketing-vs-omnichannel-understanding-the-difference",
    "comprehensive-guide-to-omnichannel-marketing",
    "omnichannel-marketing-case-study-unlocking-success-through-seamless-integration",
    "best-omnichannel-marketing-tools-enhancing-your-marketing-strategy",
    "omnichannel-digital-marketing-revolutionizing-customer-engagement",
    "email-marketing-omnichannel-boosting-engagement-and-conversions",
    "how-does-omnichannel-marketing-work-for-customers",
    "hero-how-omnichannel-marketing-can-skyrocket-your-sales",
    "unleashing-the-power-of-omnichannel-strategies-transforming-fragmented-marketing-into-seamless-success",
    "breaking-barriers-transform-your-business-with-omnichannel-marketing",
    "from-digital-dreams-to-reality-omnichannel-marketings-triumph-in-india",
    "code-maximizing-roi-with-omnichannel-marketing-strategies",
    "the-future-of-marketing-in-india-a-deep-dive-into-the-omnichannel",
    "why-is-omnichannel-important",
    "crushing-the-competition-how-omnichannel-marketing-is-giving-indian-businesses-the-edge",
    "when-did-omnichannel-start",
    "what-omni-channel-do",
    "what-omnichannel-means",
    "who-is-doing-omnichannel-well",
    "what-comes-after-omnichannel-the-evolution-of-customer-experience",
    "best-omnichannel-brands-revolutionizing-customer-experiences",
    "omnichannel-enablement-transforming-customer-engagement-in-the-digital-age",
    "omnichannel-environment-bridging-the-gap-between-businesses-and-customers",
    "omnichannel-b2b-revolutionizing-business-engagement",
    "omnichannel-business-analyst-navigating-the-modern-business-landscape",
    "omnichannel-marketing-and-social-media-revolutionizing-customer-engagement",
    "unlocking-seamless-customer-experiences-the-power-of-an-omnichannel-approach-with-hubspot",
    "omnichannel-lead-generation-maximizing-your-reach-and-impact",
    "omnichannel-how-to-pronounce-and-master-the-concept",
    "ga4-reports-builder-enhance-your-google-analytics-with-this-powerful-extension",
    "google-one-dark-web-report-rolls-out-for-users-in-india-how-it-works",
    "the-future-of-omnichannel-revolutionizing-customer-experiences",
    "omnichannel-analytics",
    // New Redirects from 404 Logs
    "how-genai-is-changing-the-landscape-of-automation",
    "genai-content-marketing-crwating-content-at-scale",
    "creating-an-omnichannel-strategy-with-genai-marketing-automation",
    "genai-automation-tools-for-seamless-content-marketing",
    "creating-compelling-campaigns-with-genai-content-marketing",
    "ai-driven-customer-experiences",
    "increase-awareness",
    // New Redirects from Logs (2025-12-30)
    "genai-automation-transforming-the-way-we-work",
    "achieving-brand-growth-with-genai-marketing-automation-2",
    "how-genai-automation-enhances-data-driven-marketing",
    "10-benefits-of-genai-marketing-automation-for-marketers",
    "boosting-seo-with-genai-content-marketing-strategies"
].map(slug => ({
    source: `/${slug}`,
    destination: `/blog/${slug}`,
    permanent: true,
})).concat([
    {
        source: '/about-us',
        destination: '/about',
        permanent: true,
    },
    {
        source: '/why-tapouts',
        destination: '/about',
        permanent: true,
    },
    {
        source: '/services/service001',
        destination: '/services',
        permanent: true,
    },
    {
        source: '/services/service002',
        destination: '/services',
        permanent: true,
    },
    {
        source: '/contact-us',
        destination: '/contact',
        permanent: true,
    },
    {
        source: '/wp-sitemap.xml',
        destination: '/sitemap.xml',
        permanent: true,
    },
    {
        source: '/wp-content/:path*',
        destination: '/',
        permanent: true,
    },
    {
        source: '/testimonials/:slug*',
        destination: '/',
        permanent: true,
    }
]);
